title: "Van Duy Nguyen (Adrian)"
description: "Senior Android Engineer | Kotlin • Jetpack Compose • Clean Architecture"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Optional: social links
github_username: DuyNguyenGit
linkedin_username: adrian-duy-nguyen

# For navigation links
header_pages:
  - index.md
  - projects.md
  - experience.md
